export const MenuChannels = {
  WINDOW_MINIMIZE: 'window-minimize',
  WINDOW_MAXIMIZE: 'window-maximize',
  WINDOW_TOGGLE_MAXIMIZE: 'window-toggle-maximize',
  WINDOW_CLOSE: 'window-close',
  WEB_TOGGLE_DEVTOOLS: 'web-toggle-devtools',
  WEB_ACTUAL_SIZE: 'web-actual-size',
  WEB_ZOOM_IN: 'web-zoom-in',
  WEB_ZOOM_OUT: 'web-zoom-out',
  WEB_TOGGLE_FULLSCREEN: 'web-toggle-fullscreen',
  OPEN_GITHUB_PROFILE: 'open-github-profile',
  MENU_EVENT: 'menu-event',
  EXECUTE_MENU_ITEM_BY_ID: 'execute-menu-item-by-id',
  SHOW_CONTEXT_MENU: 'show-context-menu',
} as const;
